config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  get 'home/new'
  get 'home/create'
  get 'home/about'
  get 'home/contact'
  get 'home/faq'
  resources :konwersja_kont
  get 'konwersja_kont/index'
  get 'konwersja_kont/:id' => 'konwersja_kont#view'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kontum.rb
class Kontum < ApplicationRecord
end

app/models/konwersja_kont.rb
class KonwersjaKont < ActiveRecord::Base
self.pluralize_table_names = false

def self.search(params)
if params[:search]
KonwersjaKont.where('Rachunek LIKE ?', "%#{params[:search]}%")
else
all
end
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :ldap_authenticatable, :registerable, 
	 :recoverable, :rememberable, :trackable, :validatable

validates :username, presence: true, uniqueness: true

before_validation :get_ldap_email
def get_ldap_email
self.email = Devise::LDAP::Adapter.get_ldap_param(self.username,"mail").first
end

#use ldap uid as primary key
before_validation :get_ldap_id

def get_ldap_id
#wlasna zmiana 
# self.id = 
#    self.id = Devise::LDAP::Adapter.get_ldap_param(self.username,"sAMAccountName").first
# orginalny wpis : nie ma uidnumber !!!
#    self.id = Devise::LDAP::Adapter.get_ldap_param(self.username,"uidnumber").first
end

#hack for remember_token

def authenticatable_token
Digest::SHA1.hexdigest(email)[0,29]
end 

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#    before_action :authenticate_user!  
    before_action :configure_permitted_parameters, if: :devise_controller?
    rescue_from DeviseLdapAuthenticatable::LdapException do |exception|
    render :text => exception, :status => 500
    end
    protect_from_forgery with: :exception


protected 
def configure_permitted_parameters
 devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def new
  end

  def create
  end

  def about
  end

  def contact
  end

  def faq
  end
end

app/controllers/konta_controller.rb
class KontaController < ApplicationController
  before_action :set_kontum, only: [:show, :edit, :update, :destroy]

  # GET /konta
  # GET /konta.json
  def index
    @konta = Kontum.all
  end

  # GET /konta/1
  # GET /konta/1.json
  def show
  end

  # GET /konta/new
  def new
    @kontum = Kontum.new
  end

  # GET /konta/1/edit
  def edit
  end

  # POST /konta
  # POST /konta.json
  def create
    @kontum = Kontum.new(kontum_params)

    respond_to do |format|
      if @kontum.save
        format.html { redirect_to @kontum, notice: 'Kontum was successfully created.' }
        format.json { render :show, status: :created, location: @kontum }
      else
        format.html { render :new }
        format.json { render json: @kontum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /konta/1
  # PATCH/PUT /konta/1.json
  def update
    respond_to do |format|
      if @kontum.update(kontum_params)
        format.html { redirect_to @kontum, notice: 'Kontum was successfully updated.' }
        format.json { render :show, status: :ok, location: @kontum }
      else
        format.html { render :edit }
        format.json { render json: @kontum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /konta/1
  # DELETE /konta/1.json
  def destroy
    @kontum.destroy
    respond_to do |format|
      format.html { redirect_to konta_url, notice: 'Kontum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kontum
      @kontum = Kontum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kontum_params
      params.require(:kontum).permit(:Id, :Rachunek, :Konto_wn_plus, :Konto_ma_plus, :Konto_wn_minus, :Konto_ma_minus, :Manual)
    end
end

app/controllers/konwersja_kont_controller.rb
class KonwersjaKontController < ApplicationController
  before_action :set_konwersja_kont, only: [:show, :edit, :update, :destroy]

  # GET /konwersja_kont
  # GET /konwersja_kont.json
  def index
@konwersja_kont = KonwersjaKont.paginate(:page => params[:page], :per_page => 10 ).search(params)
#index.html
#index.js
end

  # GET /konwersja_kont/1
  # GET /konwersja_kont/1.json
  def show
  end

  # GET /konwersja_kont/new
  def new
    @konwersja_kont = KonwersjaKont.new
  end

  # GET /konwersja_kont/1/edit
  def edit
  end

  # POST /konwersja_kont
  # POST /konwersja_kont.json
  def create
    @konwersja_kont = KonwersjaKont.new(konwersja_kont_params)

    respond_to do |format|
      if @konwersja_kont.save
        format.html { redirect_to @konwersja_kont, notice: 'Konwersja kont was successfully created.' }
        format.json { render :show, status: :created, location: @konwersja_kont }
      else
        format.html { render :new }
        format.json { render json: @konwersja_kont.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /konwersja_kont/1
  # PATCH/PUT /konwersja_kont/1.json
  def update
    respond_to do |format|
      if @konwersja_kont.update(konwersja_kont_params)
        format.html { redirect_to @konwersja_kont, notice: 'Konwersja kont was successfully updated.' }
        format.json { render :show, status: :ok, location: @konwersja_kont }
      else
        format.html { render :edit }
        format.json { render json: @konwersja_kont.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /konwersja_kont/1
  # DELETE /konwersja_kont/1.json
  def destroy
    @konwersja_kont.destroy
    respond_to do |format|
      format.html { redirect_to konwersja_kont_url, notice: 'Konwersja kont was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_konwersja_kont
      @konwersja_kont = KonwersjaKont.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def konwersja_kont_params
      params.require(:konwersja_kont).permit(:Id, :Rachunek, :Konto_wn_plus, :Konto_ma_plus, :Konto_wn_minus, :Konto_ma_minus, :Manual)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
end
end

app/helpers/home_helper.rb
module HomeHelper
def copyright_notice_year_range(start_year)

start_year =start_year.to_i
current_year = Time.new.year

if current_year > start_year && start_year > 2000
"#{start_year} - #{current_year}"
elsif start_year > 2000
"#{start_year}"
else
"#{current_year}"
end

end

end

app/helpers/konta_helper.rb
module KontaHelper
end

app/helpers/konwersja_kont_helper.rb
module KonwersjaKontHelper
end

app/views/home/_footer.html.erb
<div  class="footer">
&copy; <%= copyright_notice_year_range(2016) %> <%= link_to "MAREK OLSZEWSKI","#" %> Wszystkie Prawa Zastrzezone 
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-dark bg-primary">

<div class="container-fluid">
       <ul class="nav navbar-nav">
      <li class="dropdown">
	    <a href="" class="btn btn-primary dropdown-toggle btn-lg active" style="margin-left:25px;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Intranet <span class="glyphicon glyphicon-menu-down"></span></a>
    	<ul class="dropdown-menu">
        <li><%= link_to 'Strona główna', root_path, class: :"btn btn-default btn-lg"  %></li>
	    <li><%= link_to 'O aplikacji', home_about_path, class: :"btn btn-default btn-lg" %></li>
	    <li><%= link_to 'FAQ', home_contact_path, class: :"btn btn-default btn-lg"  %></li>
        </ul>
      </li>
	  
      <% if user_signed_in? %>
      <li role="presentation"><%= link_to 'Konwersja', konwersja_kont_index_path, class: :"btn btn-primary btn-lg active" %></li>
      <% end %>
   
      <% if user_signed_in? && current_user.username == "administrator" %>
      <li role="presentation"><%= link_to 'Administracja', "#" , class: :"btn btn-success btn-lg active" %></li>
      <% end %>
    </ul>
	<ul class="nav navbar-nav navbar-right">
    <% if not user_signed_in? %>
    <li role="presentation"><%= link_to ' Logowanie', new_user_session_path ,class: :"btn btn-primary btn-lg active glyphicon glyphicon-log-in", style: :"margin-right:25px;"  %></li>
    <% end %>
   
    <% if user_signed_in? %>
    <li role="presentation"><%= link_to ' Wylogowanie ', destroy_user_session_path, class: :"btn btn-danger btn-lg active glyphicon glyphicon-log-out",name: :"logout", id: :"logout",  method: :delete, data: {confirm: :"Czy jesteś pewny ?"} %></li>
    <li role="presentation"><%= link_to " " + current_user.username, "", class: :"btn btn-info btn-lg active glyphicon glyphicon-user",style: :"margin-right:25px;" %></li>
    <% end %>
	</ul>
  </div>

</nav>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/create.html.erb
<h1>Home#create</h1>
<p>Find me in app/views/home/create.html.erb</p>

app/views/home/faq.html.erb
<h1>Home#faq</h1>
<p>Find me in app/views/home/faq.html.erb</p>

app/views/home/index.html.erb
<h1>Witaj w nowej wersji aplikacji Intranet</h1>
<p>Niebawem nowe aplikacje</p>

app/views/home/konwersja.html.erb
<h1>Witaj w Konwersja</h1>
<p>Niebawem cała aplikacja</p>

app/views/home/new.html.erb
<h1>Home#new</h1>
<p>Find me in app/views/home/new.html.erb</p>

app/views/konta/_form.html.erb
<%= form_for(kontum) do |f| %>
  <% if kontum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kontum.errors.count, "error") %> prohibited this kontum from being saved:</h2>

      <ul>
      <% kontum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Id %>
    <%= f.text_field :Id %>
  </div>

  <div class="field">
    <%= f.label :Rachunek %>
    <%= f.text_field :Rachunek %>
  </div>

  <div class="field">
    <%= f.label :Konto_wn_plus %>
    <%= f.text_field :Konto_wn_plus %>
  </div>

  <div class="field">
    <%= f.label :Konto_ma_plus %>
    <%= f.text_field :Konto_ma_plus %>
  </div>

  <div class="field">
    <%= f.label :Konto_wn_minus %>
    <%= f.text_field :Konto_wn_minus %>
  </div>

  <div class="field">
    <%= f.label :Konto_ma_minus %>
    <%= f.text_field :Konto_ma_minus %>
  </div>

  <div class="field">
    <%= f.label :Manual %>
    <%= f.check_box :Manual %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/konta/edit.html.erb
<h1>Editing Kontum</h1>

<%= render 'form', kontum: @kontum %>

<%= link_to 'Show', @kontum %> |
<%= link_to 'Back', konta_path %>

app/views/konta/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Konta</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Rachunek</th>
      <th>Konto wn plus</th>
      <th>Konto ma plus</th>
      <th>Konto wn minus</th>
      <th>Konto ma minus</th>
      <th>Manual</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @konta.each do |kontum| %>
      <tr>
        <td><%= kontum.Id %></td>
        <td><%= kontum.Rachunek %></td>
        <td><%= kontum.Konto_wn_plus %></td>
        <td><%= kontum.Konto_ma_plus %></td>
        <td><%= kontum.Konto_wn_minus %></td>
        <td><%= kontum.Konto_ma_minus %></td>
        <td><%= kontum.Manual %></td>
        <td><%= link_to 'Show', kontum %></td>
        <td><%= link_to 'Edit', edit_kontum_path(kontum) %></td>
        <td><%= link_to 'Destroy', kontum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kontum', new_kontum_path %>

app/views/konta/new.html.erb
<h1>New Kontum</h1>

<%= render 'form', kontum: @kontum %>

<%= link_to 'Back', konta_path %>

app/views/konta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @kontum.Id %>
</p>

<p>
  <strong>Rachunek:</strong>
  <%= @kontum.Rachunek %>
</p>

<p>
  <strong>Konto wn plus:</strong>
  <%= @kontum.Konto_wn_plus %>
</p>

<p>
  <strong>Konto ma plus:</strong>
  <%= @kontum.Konto_ma_plus %>
</p>

<p>
  <strong>Konto wn minus:</strong>
  <%= @kontum.Konto_wn_minus %>
</p>

<p>
  <strong>Konto ma minus:</strong>
  <%= @kontum.Konto_ma_minus %>
</p>

<p>
  <strong>Manual:</strong>
  <%= @kontum.Manual %>
</p>

<%= link_to 'Edit', edit_kontum_path(@kontum) %> |
<%= link_to 'Back', konta_path %>

app/views/konwersja_kont/_form.html.erb
<%= form_for(@konwersja_kont) do |f| %>
  <% if @konwersja_kont.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@konwersja_kont.errors.count, "error") %> prohibited this konwersja_kont from being saved:</h2>

      <ul>
      <% @konwersja_kont.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Id %><br>
    <%= f.number_field :Id %>
  </div>
  <div class="field">
    <%= f.label :Rachunek %><br>
    <%= f.text_field :Rachunek %>
  </div>
  <div class="field">
    <%= f.label :Konto_wn_plus %><br>
    <%= f.text_field :Konto_wn_plus %>
  </div>
  <div class="field">
    <%= f.label :Konto_ma_plus %><br>
    <%= f.text_field :Konto_ma_plus %>
  </div>
  <div class="field">
    <%= f.label :Konto_wn_minus %><br>
    <%= f.text_field :Konto_wn_minus %>
  </div>
  <div class="field">
    <%= f.label :Konto_ma_minus %><br>
    <%= f.text_field :Konto_ma_minus %>
  </div>
  <div class="field">
    <%= f.label :Manual %><br>
    <%= f.check_box :Manual %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/konwersja_kont/_form_search.html.erb
<%= form_tag konwersja_kont_path, :method => 'get', :id => "konwersja_kont_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Szukaj", :name => nil %>
  </p>
<% end %>

app/views/konwersja_kont/edit.html.erb
<h1>Editing Konwersja Kont</h1>

<%= render 'form' %>

<%= link_to 'Show', @konwersja_kont %> |
<%= link_to 'Back', konwersja_kont_index_path %>

app/views/konwersja_kont/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista Kont dla konwersji</h1>

<div class="table">
<%= form_tag  konwersja_kont_index_path, :method => 'get',  :id => "konwersja_kont_search" do %>
<% hidden_field_tag :direction, params[:direction] %>
<% hidden_field_tag :sort, params[:sort] %>
<p>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Szukaj", :name=> nil %>
</p>
<div id="konwersja_kont"><%= render 'konwersja_kont' %></div>
<div class="pagination"><%= will_paginate @konwersja_kont %></div>
<% end %>

<table class="table-hover table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Rachunek</th>
      <th>Konto wn plus</th>
      <th>Konto ma plus</th>
      <th>Konto wn minus</th>
      <th>Konto ma minus</th>
      <th>Manual</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @konwersja_kont.each do |konwersja_kont| %>
      <tr>
        <td><%= konwersja_kont.Id %></td>
        <td><%= konwersja_kont.Rachunek %></td>
        <td><%= konwersja_kont.Konto_wn_plus %></td>
        <td><%= konwersja_kont.Konto_ma_plus %></td>
        <td><%= konwersja_kont.Konto_wn_minus %></td>
        <td><%= konwersja_kont.Konto_ma_minus %></td>
        <td><%= konwersja_kont.Manual %></td>
        <td><%= link_to 'Show', konwersja_kont %></td>
        <td><%= link_to 'Edit', edit_konwersja_kont_path(konwersja_kont) %></td>
        <td><%= link_to 'Destroy', konwersja_kont, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Konwersja kont', new_konwersja_kont_path %>

app/views/konwersja_kont/new.html.erb
<h1>New Konwersja Kont</h1>

<%= render 'form' %>

<%= link_to 'Back', konwersja_kont_path %>

app/views/konwersja_kont/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @konwersja_kont.Id %>
</p>

<p>
  <strong>Rachunek:</strong>
  <%= @konwersja_kont.Rachunek %>
</p>

<p>
  <strong>Konto wn plus:</strong>
  <%= @konwersja_kont.Konto_wn_plus %>
</p>

<p>
  <strong>Konto ma plus:</strong>
  <%= @konwersja_kont.Konto_ma_plus %>
</p>

<p>
  <strong>Konto wn minus:</strong>
  <%= @konwersja_kont.Konto_wn_minus %>
</p>

<p>
  <strong>Konto ma minus:</strong>
  <%= @konwersja_kont.Konto_ma_minus %>
</p>

<p>
  <strong>Manual:</strong>
  <%= @konwersja_kont.Manual %>
</p>

<%= link_to 'Edit', edit_konwersja_kont_path(@konwersja_kont) %> |
<%= link_to 'Back', konwersja_kont_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intranet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= render 'home/header' %>
</div>

<div class="container">
<p role="alert">
<%= notice %>
<%= alert %>
</p>
</div>

<div class="container">
<div class="jumbotron">
<%= yield %>
</div>
</div>

<div class="container">
<div class="footer">
<%= render 'home/footer' %>
</div>
</div>
</body>
</html>